### ISSUE TITLE
No Intro to Robotics

### ISSUE THREAD

**Issue by AbhinavMadahar** [serialscoper101/MHSCompSci#1]
I know it's not really a computer science class, but it uses a lot of programming, and Advanced Robotics has a page

**Comment by rvolyar** [comment]
I plan to add more content to this page but for now Mr. Farrell didn't give
me anything to put up yet. Would you be interested working on that charity
project we're going to talk about on monday?

**Comment by AbhinavMadahar** [comment]
sure
