### ISSUE TITLE
It should use Markdown instead of Word Docs

### ISSUE THREAD

**Issue by AbhinavMadahar** [serialscoper101/MHSCompSci#2]
That way the files can all be opened without downloading them (because Markdown is converted into HTML) and look better.

Have the CS1 students manually convert the Word files to Markdown under the guise that it's a new unit in the class. After all, it's not like they're doing much anyway, and at least Markdown is used (unlike BASIC). Then, have them push the changes to GitHub.

**Comment by rvolyar** [comment]
I agree that opening files is a much better than downloading them. What about using the google drive viewer to do this?
Take [this](https://docs.google.com/viewer?url=http://www.mhscompsci.com/themes/october-theme/assets/courses/ap/Class%20Projects/MBS_Fish_of_Death_PROJECT.doc) document for example. I can write a regex that would replace all links like
`http://www.mhscompsci.com/themes/october-theme/assets/courses/ap/Class%20Projects/MBS_Fish_of_Death_PROJECT.doc`
to
`https://docs.google.com/viewer?url=http://www.mhscompsci.com/themes/october-theme/assets/courses/ap/Class%20Projects/MBS_Fish_of_Death_PROJECT.doc`

It will be much faster and I think better as students can save the document to drive, view and print straight from the browser.

**Comment by AbhinavMadahar** [comment]
Good idea.
